name: cosmetics_store
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.11.0-16.0.dev

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.1.0
  meta: ^1.17.0
  flutter_bloc: ^9.1.1
  image_picker: ^1.2.0
  uuid: ^4.5.2
  bloc_test: ^10.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/icons/
    - assets/images/default/
    - assets/images/
